// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNzKA_00bWCNA7p_vBwb1T3Rdmh2S6EGU',
    appId: '1:958398223685:web:a6b936fff87a23ec2c5a2c',
    messagingSenderId: '958398223685',
    projectId: 'fitnessapp-54747',
    authDomain: 'fitnessapp-54747.firebaseapp.com',
    storageBucket: 'fitnessapp-54747.appspot.com',
    measurementId: 'G-NHQFPKTT0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhTDY0LIZp103YlVJH3nntQ0KVFdn48c',
    appId: '1:958398223685:android:162bb30a66177bc12c5a2c',
    messagingSenderId: '958398223685',
    projectId: 'fitnessapp-54747',
    storageBucket: 'fitnessapp-54747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm65vQKBiDcOSff9-HzO4pjoEMpcAmcWI',
    appId: '1:958398223685:ios:8823f0adf953aa1e2c5a2c',
    messagingSenderId: '958398223685',
    projectId: 'fitnessapp-54747',
    storageBucket: 'fitnessapp-54747.appspot.com',
    androidClientId: '958398223685-ue6qj6dhkgpmskbei877psfbma0clb0o.apps.googleusercontent.com',
    iosClientId: '958398223685-3voegl6jbfh1jargh6vanbrlgpuvdc52.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );
}
